### ISSUE TITLE
Unknown option '--reporter'

### ISSUE THREAD

**Issue by vvedachalam** [hdorgeval/testcafe-reporter-cucumber-json#1]
Hi
Thanks for the report. I can run the report separately but if i add the below along with the testcafe command line, i am getting error - Unknown option --reporter
node ./node_modules/.bin/cucumber-js --reporter cucumber-json:reports/report.json --reporter-app-name='MAI AI' --reporter-app-version='0.9.1'
However this works: node ./node_modules/.bin/cucumber-js
Any idea what am I missing?

**Comment by hdorgeval** [comment]
Hi @vvedachalam, this reporter is intended to work with TestCafe only. This reporter produces the same json format as native json cucumber-js reporter. 

The testcafe command line should look like this:
```sh
testcafe chrome tests/**/*.spec.js --reporter cucumber-json:reports/report.json --reporter-app-name='My App' --reporter-app-version='x.y.z'
```

You should not call `node ./node_modules/.bin/cucumber-js`.  
The `--reporter` option does not exist in cucumber-js.

**Comment by vvedachalam** [comment]
HI @hdorgeval , Thanks for the quick response. I didnt get email notification for some reason about your response. Yes, that's what I got confused as I never seen --reporter option. But why should we use testcafe  cmd by mentioning spec name? We should be able to run the features or tags right? Or you just use cucumber for reporting and not for Gherkin style BDD test framework?
