### ISSUE TITLE
Missing history test suite in the report

### ISSUE THREAD

**Issue by herveroche** [hdorgeval/testcafe-reporter-cucumber-json#14]
I have more than one file un my directory "Feature" and they are not displayed when i generated report...

I'll add some screenshot:
![image](https://user-images.githubusercontent.com/30661964/72073582-7bdf6800-32f0-11ea-832c-38c1ece8c9d0.png)

Here my reporter code:
```
const report = require('multiple-cucumber-html-reporter');
const path = require('path');
const projectName = path.basename(__dirname);
const projectVersion = process.env.npm_package_version;
const reportGenerationTime = new Date().toISOString();

report.generate({
    reportName: 'TestCafe Report',
    jsonDir: 'reports',
    reportPath: 'reports',
    openReportInBrowser: true,
    disableLog: true,
    displayDuration: true,
    durationInMS: true,
    customData: {
        title: 'Run info',
        data: [
            { label: 'Project', value: `${projectName}` },
            { label: 'Release', value: `${projectVersion}` },
            { label: 'Report Generation Time', value: `${reportGenerationTime}` },
        ],
    },
});
```

Finally my vew in the browser:
![image](https://user-images.githubusercontent.com/30661964/72073672-a5988f00-32f0-11ea-94aa-41fb8d2939ca.png)

Or maybe I missing something... 

Last clue: I execute my test one by one like npm run test1 than npm run test2 etc ... The reporter is call only at the end of these test

**Comment by hdorgeval** [comment]
Hi @herveroche, do you think it is possible that you send me the `report.json` file, so that I can understand what is happening?

**Comment by hdorgeval** [comment]
Hi @herveroche, I think I misunderstood your report. As far as I understand, each time you run your test the generated report.json file overwrites the previously generated. 

So when you run the report, you only see the result of the last run. 

What I suggest is that you modify your run scripts to generate a different file at each run:

```script
test1: testcafe chrome --reporter cucumber-json:reports/report1.json,
test2: testcafe chrome --reporter cucumber-json:reports/report2.json,
test3: testcafe chrome --reporter cucumber-json:reports/report3.json,
```

Then, once all tests have run, the `npm run report` should merge all generated files.

**Comment by hdorgeval** [comment]
Hi @herveroche , the latest version `v6.0.4` should solve your issue. See the [breaking changes](https://github.com/hdorgeval/testcafe-reporter-cucumber-json/blob/master/CHANGELOG.md#breaking-changes).
