### ISSUE TITLE
Report is not getting the OS and Browser(name & version) information.

### ISSUE THREAD

**Issue by JoanEsquivel** [hdorgeval/testcafe-reporter-cucumber-json#20]
Hi there guys,

Thanks for this amazing library. 

I am trying to use it in my project but I am getting issues getting the OS and Browser(name & version) information. 

I followed all the steps but  I am not sure if I should pass those params somewhere else.

Thanks a lot for your support. 

Joan.

**Comment by JoanEsquivel** [comment]
![Report issue](https://user-images.githubusercontent.com/48256183/77453738-41e51480-6dbd-11ea-92c7-e84065f62d77.PNG)

**Comment by hdorgeval** [comment]
Hi @JoanEsquivel , thank you for using this library, do you have any messages like this `testcafe-reporter-cucumber-json: cannot get the Platform name from input string ...` in the console?

This could help
Thanks

**Comment by JoanEsquivel** [comment]
Hi @hdorgeval , thanks for the support. 

I don't, that is the weird fact. Let me show you an SS of the console and then the result(I changed the scenario to have all the tests passing).

![image](https://user-images.githubusercontent.com/48256183/77458560-fe41d900-6dc3-11ea-8dbd-6fb2ebdf549e.png)

**Comment by hdorgeval** [comment]
Hi @JoanEsquivel , all you have done seems correct to me. I will publish a new version that will print the user agent sent by TestCafe to this reporter, so that I can make the necessary updates

**Comment by JoanEsquivel** [comment]
Thanks @hdorgeval ! 

Really appreciate your help.

**Comment by hdorgeval** [comment]
@JoanEsquivel : it would be greater if you could send me the json file generated in the reports folder

**Comment by JoanEsquivel** [comment]
@hdorgeval sure. 

Preview of the matadata you'll find.


"metadata": {
      "app": {
        "name": "'My_Test'",
        "version": "'1'"
      },
      "browser": {
        "name": "unknown",
        "version": "unknown"
      },
      "device": "Windows 10",
      "platform": {
        "name": "windows",
        "version": "unknown"
      }
[report.zip](https://github.com/hdorgeval/testcafe-reporter-cucumber-json/files/4376920/report.zip)

**Comment by hdorgeval** [comment]
@JoanEsquivel , thank you very much, I have located the problem: it is a bug on my side. I will ping you as soon as I have fixed it.

**Comment by JoanEsquivel** [comment]
@hdorgeval amazing. Thank you!

**Comment by hdorgeval** [comment]
Hi @JoanEsquivel , I have published v5.0.0 on npm that should solve your issue.
Please tell me if this new version is working for you.
Thnks

**Comment by JoanEsquivel** [comment]
Hi @hdorgeval 

I just wanted to confirm that it's fixed! 

Thank you very much! Have an excellent day.
