### ISSUE TITLE
no difference between "chrome" and "chrome:emulation:device=iphone X" 

### ISSUE THREAD

**Issue by guiyomh** [hdorgeval/testcafe-reporter-cucumber-json#21]
Hello,

I launch testcafé with the following browsers `"chrome:headless,chrome:headless:emulation:device=iphone X"` I was expecting to see twice the features and scenarion in the report (mobile and desktop).

But I only do it once and there's no desktop/mobile distinction.

![image](https://user-images.githubusercontent.com/363162/77817534-d1473c00-70cb-11ea-8507-8efb4c51ad9f.png)

I used

- "testcafe": "^1.8.3", 
- "testcafe-reporter-cucumber-json": "^5.0.0",

**Comment by hdorgeval** [comment]
Hi @guiyomh, thank you for your feedback. This reporter has not been designed to work either in concurrency mode or with several browsers declared on the same command-line.

A workaround could be to have separate npm script for each browser with a report file name different for each script.

If you think this reporter is lacking the multi/concurrency-reporting functionality, please let me know.
PR is welcomed if you want to contribute :)

**Comment by hdorgeval** [comment]
Hi @guiyomh : this issue has been fixed in version `v6.0.4`. See [breaking changes](https://github.com/hdorgeval/testcafe-reporter-cucumber-json/blob/master/CHANGELOG.md#breaking-changes).

**Comment by guiyomh** [comment]
thx
