### ISSUE TITLE
Provider an API to pass parameters

### ISSUE THREAD

**Issue by combmag** [hdorgeval/testcafe-reporter-cucumber-json#26]
Currently the only way to pass arguments such as `reporter-json-folder` is to use testcafe CLI, 

Currently we use the testcafe API to run testcafe tests. Is there anyway that we can override the reporter-json-folder without passing it as a CLI arg?

**Comment by hdorgeval** [comment]
Hi @c-magri , thanks for your feedback. I will update the reporter to handle your issue through a configuration file. I do my best to provide you a solution asap.

**Comment by hdorgeval** [comment]
Hi @c-magri , I have pushed [v6.2.0](https://github.com/hdorgeval/testcafe-reporter-cucumber-json/releases/tag/v6.2.0) that should fix your issue.

**Comment by c-magri** [comment]
works like a charm thanks!
