### ISSUE TITLE
JSON folder and file not created

### ISSUE THREAD

**Issue by deepakarya74** [hdorgeval/testcafe-reporter-cucumber-json#27]
I followed the documentation provided on this link. https://www.npmjs.com/package/testcafe-reporter-cucumber-json
I ran the below command, the folder "cucumber-json-reports"  and JSON file not created. 

`npm run tc:chrome tests/sample-test.js --reporter cucumber-json`

**package.json information below**
script{
"tc:chrome": "export NODE_ENV='development' && ./node_modules/.bin/testcafe chrome -e"
}
 "dependencies": {
    "@ffmpeg-installer/ffmpeg": "^1.0.20",
    "dotenv": "^8.2.0",
    "minimist": "^1.2.5",
    "testcafe": "^1.9.3",
    "testcafe-react-selectors": "^4.0.0",
    "testcafe-reporter-cucumber-json": "^6.2.0",
    "testcafe-reporter-slack-custom": "^1.3.0"
  },
  "devDependencies": {
    "multiple-cucumber-html-reporter": "^1.18.0"
  }

**Comment by hdorgeval** [comment]
Hi @deepakarya74 , I think the command should be:

```sh
npm run tc:chrome -- tests/sample-test.js --reporter cucumber-json
```

**Comment by deepakarya74** [comment]
Thanks for your quick response.
I found the solution, updated the script in package.json as mentioned below, after that it worked fine. 
Running in Local
**Package.JSON**
"tc:chrome": "export NODE_ENV='development' && ./node_modules/.bin/testcafe chrome -e --reporter cucumber-json"

**Command Line**
`npm run tc:chrome tests/sample-test.js`

**Additional Information**- In case if anyone is using ".testcaferc.json" config file, they can update the file way mentioned below.
`"reporter": [
        {
            "name": "cucumber-json"
        }
]`

**Comment by deepakarya74** [comment]
Thanks
