### ISSUE TITLE
warning testcafe-reporter-cucumber-json@0.3.1: The engine "vscode" appears to be invalid.

### ISSUE THREAD

**Issue by royriojas** [hdorgeval/testcafe-reporter-cucumber-json#3]
After a fresh install of this plugin the following error is shown in the console:

```
warning testcafe-reporter-cucumber-json@0.3.1: The engine "vscode" appears to be invalid.
```

https://github.com/hdorgeval/testcafe-reporter-cucumber-json/blob/c5c987c2676c478d73001e0e9bbc76751a44ac35/package.json#L56

**Comment by hdorgeval** [comment]
Hi @royriojas, thank you for your feedback. I will  investigate your issue as soon as possible.

**Comment by hdorgeval** [comment]
Hi @royriojas : could you tell me is this is still an issue in v1.0.0?
