### ISSUE TITLE
Should testcafe better be a peer dependency

### ISSUE THREAD

**Issue by royriojas** [hdorgeval/testcafe-reporter-cucumber-json#4]
Please consider moving testcafe as peer dependency instead of dependency.

https://github.com/hdorgeval/testcafe-reporter-cucumber-json/blob/c5c987c2676c478d73001e0e9bbc76751a44ac35/package.json#L47

**Comment by hdorgeval** [comment]
Hi @royriojas : thanks again for your great feedback. I will correct this asap.

**Comment by hdorgeval** [comment]
Hi @royriojas : this issue has been corrected in v1.0.0
