### ISSUE TITLE
testcafe-reporter-cucumber-json  reports require test cafe to use cucumber?

### ISSUE THREAD

**Issue by skullz03** [hdorgeval/testcafe-reporter-cucumber-json#6]
Hi, 

Just wondering to use this library- does the testCafe project need to have cucumber integrated? I have pure testcafe project(no cucumber), would I be able to leverage the benefits of this?

**Comment by hdorgeval** [comment]
Hi @skullz03, this reporter creates a JSON file in a format that is similar to the JSON reporter of CucumberJS.

This reporter has no dependency on cucumberjs. It's just a JSON reporter.

The added value of this reporter is that there are great packages that can transform the generated json file into a static Web site. You can use any of these packages, but this reporter has been designed to smoothly integrates with `multiple-cucumber-html-reporter`.

**Comment by RemigiusL** [comment]
Hi @skullz03,  
      

-   After installing your **Cucumber JSON TestCafe Reporter (beta)** npm package. I'm trying to get the HTML report using your given comment **testcafe chrome ./path-to-tests/*(.js|.testcafe|.ts) --reporter cucumber-json:reports/report.json --reporter-app-name='My App' --reporter-app-version='x.y.z'** but not able to get the report.

**It says, ERROR The provided "cucumber-JSON" reporter does not exist. Check that you have specified the report format correctly.** 

Could you pls help me out?
