### ISSUE TITLE
When use Browserstack, the platform is missing

### ISSUE THREAD

**Issue by herveroche** [hdorgeval/testcafe-reporter-cucumber-json#8]
When we use browserstack we cannot get the plateform :

testcafe-reporter-cucumber-json: cannot get the Platform name from input string : 'Chrome 75.0.3770 / Windows 10.0.0 (https://automate.browserstack.com/builds/1f90795f6e1078f0dca1b94929a8d372c60970d5/sessions/98a8e7718381c14a5c6c64afe26babb7063cf7d3)'

Or we get all the things needed pour do this.

**Comment by hdorgeval** [comment]
Hi @herveroche, thank you very much for your feedback. I will try to fix this asap, though I am still on holidays

I cannot access to the above browserstack link

**Comment by herveroche** [comment]
Don't worried I just copy/paste the warn log:
It more like this: 
`testcafe-reporter-cucumber-json: cannot get the Platform name from input string : 'Chrome 75.0.3770 / Windows 10.0.0 (https://automate.browserstack.com/builds/1f90795f6e1078f0dca1b94929a8d372c60970d5/sessions/98a8e7718381c14a5c6c64afe26babb7063cf7d3)'`

**Comment by hdorgeval** [comment]
Hi @herveroche, the fix has been deployed in v2.0.0 on npm. Could you give it a try and let me know if it works for you?

**Comment by hdorgeval** [comment]
Hi @herveroche, I will close this issue since there is no feedback on your side. 
Do not hesitate to re-open it if the latest version of the reporter does not solve this issue.

**Comment by herveroche** [comment]
Perfect ;)

Sorry for the delay !

**Comment by VoohaN** [comment]
Hi @hdorgeval, I see the same issue on the latest testcafe reporter cucumber json: testcafe-reporter-cucumber-json: cannot get the Platform name from input string 'Chrome 92.0.4515.40 / Windows 10 ( https://automation.lambdatest.com/logs/?sessionID=c905f49f9ce04dd6a0f2999adbdccb19 )' on the latest version. Could you please take a look? thanks.

**Comment by sinadenmark** [comment]
Can someone explain how to fix this ?

**Comment by VoohaN** [comment]
@sinadenmark  try changing the line here to parts[1] instead of parts.pop().
https://github.com/hdorgeval/testcafe-reporter-cucumber-json/blob/4380ddf6ff1fe308612a4af157bc940318cedb66/src/user-agent-parser.ts#L37

**Comment by VoohaN** [comment]
is that working fine? @sinadenmark

**Comment by sinadenmark** [comment]
no
